1. Create a python program to find duplicate files by content. User will 
input path and it will scan all directories, sub-directories to find all 
duplicates files.
Delete the found duplicate file.
[Hint: use hashlib]

In [12]:
import os
path_p = input("Enter your path :")
files_list = os.listdir(path = path_p)
files_list

Enter your path :C:/Users/sodatta/OneDrive - ALLEGIS GROUP/Documents/Test/


['test1.txt', 'test2.txt']

In [13]:
import hashlib
list1=[]
for i in files_list:
    file_obj=open(path_p+i,'r')
    content=file_obj.read()
    file_obj.close()
    encode_content=content.encode()
    list1.append(hashlib.sha256(encode_content).hexdigest())

In [14]:
new_dic =dict(zip(files_list,list1))
new_dic

{'test1.txt': '66a045b452102c59d840ec097d59d9467e13a3f34f6494e539ffd32c1bb35f18',
 'test2.txt': '185f8db32271fe25f561a6fc938b2e264306ec304eda518007d1764826381969'}

In [1]:
for i in new_dic:
    print(i)

NameError: name 'new_dic' is not defined

In [16]:
for i in new_dic:
    file_path=i
    abc_path = os.path.join(path_p,file_path)
    print(abc_path)

C:/Users/sodatta/OneDrive - ALLEGIS GROUP/Documents/Test/test1.txt
C:/Users/sodatta/OneDrive - ALLEGIS GROUP/Documents/Test/test2.txt


In [17]:
for i in new_dic:
    file_path=i
    abc_path = os.path.join(path_p,file_path)
    os.remove(abc_path)

In [18]:
os.listdir(path_p)

[]

2. Generate random Password with exact length = 6, with minimum 1 
uppercase, 2 lowercase, 2 digits, and remaining special characters.
Using these packages [random, strings]

In [19]:
import random
import string

In [28]:
random_lowercase1=random.choice(string.ascii_lowercase)
random_lowercase2=random.choice(string.ascii_lowercase)
random_uppercase=random.choice(string.ascii_uppercase)
digit1=random.randint(0,9)
digit2=random.randint(0,9)
special_list="!@#$%^&*"
random_1=random.choices(special_list,k=1)

password_list=[random_lowercase1,random_lowercase2,random_uppercase,str(digit1),str(digit2),random_1[0]]

random.shuffle(password_list)
password=""

for i in password_list:
    password+=i
print("Your random generated password is :{}".format(password))

Your random generated password is :@z21Mf


8. Create a given Matrix:
[  A,     B,     C,       D
   E,      F,     G,       H
    I,      a,      K,       L
   M,    N,     o,       P
   Q,     R,      S,       T
   U,     0,     W,      O ]
Replace all the vowels by np.nan
A, E, I, O U  -- >  np.nan
Return the count of the missing values

In [40]:
import numpy as np
arr_1=np.array([['a','b','c','d'],
               ['e','f','g','h'],
               ['i','j','k','l'],
               ['m','n','o','p'],
               ['q','r','s','t'],
               ['u','v','w','x']
              ])

In [41]:
arr_1.shape

(6, 4)

In [42]:
list1=['a','e','i','o','u']

In [43]:
for i in range(0,6):
    for j in range(0,4):
        if arr_1[i][j] in list1:
            print(arr_1[i][j])
            arr_1[i][j]=np.nan
count=0
for i in range(0,6):
    for j in range(0,4):
        if arr_1[i][j]==np.nan:
            count=count+1
print(count)

a
e
i
o
u
0


In [44]:
arr_1

array([['n', 'b', 'c', 'd'],
       ['n', 'f', 'g', 'h'],
       ['n', 'j', 'k', 'l'],
       ['m', 'n', 'n', 'p'],
       ['q', 'r', 's', 't'],
       ['n', 'v', 'w', 'x']], dtype='<U1')

5.Given two arrays, find their intersection. Examples:
Input:  arr1[] = [1, 3, 4, 5, 7]
             arr2[] = [2, 3, 5, 6]

In [54]:
arr2=np.array([1,3,4,5,7])
arr3=np.array([2,3,5,6])
intersection1=np.intersect1d(arr2,arr3)
print("The intersection is",intersection1)

The intersection is [3 5]


6.Create a 7 x 7 2D array having only multiples of 7. And return the last element of the same

In [73]:
import numpy as np
arr_4 =np.arange(0,49).reshape(7,7)
arr_4*=7

In [74]:
arr_4

array([[  0,   7,  14,  21,  28,  35,  42],
       [ 49,  56,  63,  70,  77,  84,  91],
       [ 98, 105, 112, 119, 126, 133, 140],
       [147, 154, 161, 168, 175, 182, 189],
       [196, 203, 210, 217, 224, 231, 238],
       [245, 252, 259, 266, 273, 280, 287],
       [294, 301, 308, 315, 322, 329, 336]])

In [75]:
arr_4[-1,-1] # return the last element of the 2d array

336

7. Checker Board Patten using Numpy:


   [   1   0   1   0   1   0   1
   
    0   1   0   1   0   1   0
    
    1   0   1   0   1   0   1
    
    0   1   0   1   0   1   0
    
    1   0   1   0   1   0   1  ]

In [66]:
n3=int(input("Enter value:"))
arr_3= np.ones((n3, n3),dtype="int16")
arr_3[1::2, ::2] = 0
arr_3[::2, 1::2] = 0
print(arr_3)

Enter value:10
[[1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]]


4.Python program to get the sum of every cubed value and its previous 
integer. 

In [4]:
num = int(input("Enter Number :"))
cube=0
for i in range(1,num):
    k=num-1
    cube += (i**3)
print(cube)
print((cube)+(cube-1))
print(cube+k)

Enter Number :78
9018009
18036017
9018086


Create 2D array and update the same 2D array provided that every 
prime number position should be replaced by cube of the positioned 
number.

In [52]:
import numpy as np
import sympy
n1,n2=int(input("Give your start value :")),int(input("Give your end value :"))
arr_6 = np.arange(n1,n2).reshape(3,3)
arr_6

Give your start value :0
Give your end value :9


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
# reshaping the input into 1d array
arr_shape = arr_6.reshape(9)

In [54]:
arr_shape

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
for i in range(len(arr_shape)):
    if sympy.isprime(arr_shape[i]):
        arr_shape[i]=arr_shape[i]**3

In [56]:
arr_shape

array([  0,   1,   8,  27,   4, 125,   6, 343,   8])

In [57]:
final_array=arr_shape.reshape(3,3)

In [64]:
print(final_array)

[[  0   1   8]
 [ 27   4 125]
 [  6 343   8]]
